Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.forward_port 8180, 8180
  
  config.vm.customize ["modifyvm", :id, "--memory", 1024]  
  
  config.vm.provision :puppet, :module_path => "../../" do |puppet|
     puppet.manifests_path = "."
     puppet.manifest_file  = "init.pp"
  end
end
