Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.forward_port 8780, 8780
  
  config.vm.customize ["modifyvm", :id, "--memory", 2048]  
  
  config.vm.provision :puppet, :module_path => "../../" do |puppet|
     puppet.manifests_path = "."
     puppet.manifest_file  = "init.pp"
  end
end
